### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by JMskch** [ln-markets/umbrel#30]
**Describe the bug**

After clicking on Login, the below error show up:
![image](https://user-images.githubusercontent.com/67028235/153070989-a2f3d9db-914b-4d7b-9936-b8a650042610.png)

Version: 1.5.1

**Comment by RomainRouphael** [comment]
Hey,

Can you upgrade to the latest version of Umbrel and uninstall / install LN Markets app?
This should fix it.

Best,
Romain

**Comment by JMskch** [comment]
Hey,

it didnt help. Still the same

**Comment by RomainRouphael** [comment]
Hey,

Ok thanks, we did it a fix, still having this issue with Umbrel/LNM App last version?

**Comment by JMskch** [comment]
Hey,

1. upgraded Umbrel
2. reinstalled LNMarkets

Still the same error on Firefox. Nothing(even logon screen) loads on other browsers like chrome, brave and edge.

**Comment by RomainRouphael** [comment]
Hey,

Sorry but I don't know how to reproduce this error: works fine for me with latest Umbrel version..
Other Umbrel apps are working fine?

**Comment by JMskch** [comment]
May be I can try to find some logs through ssh if exists. Just let me know where. Thanks.

Does it work for you also on chrome?

**Comment by RomainRouphael** [comment]
Yes it also works on Chrome for me.

Could you try this maybe?
https://umbrelinfo.gitlab.io/troubleshooting.html#one-umbrel-app-do-not-start-or-it-cant-be-installed

**Comment by JMskch** [comment]
Those commands messed up my node little bit (few hours of debugging, synchro of wallet was stucked) and it didn't help.

Still the same behaviour. Strange.

but thanks anyway

**Comment by JMskch** [comment]
fyi, I found out, where was the issue. I was accessing umbrel through IP not umbrel.local, because I had some issues in past with this domain name as my node is connected through wifi.
